# sample dev block in the toml
# note: each of these fields are OPTIONAL and should only be used if you need an override
[dev]
  command = "npm run client" # Command to start your dev server
  targetPort = 5173 # # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "client/dist" # If you use a _redirect file, provide the path to your static content folder
[functions]
  included_files = ["./numsdrums.mp3"]